---
global:
  fix_meta_yml_modules:
    - HTTP::Request::AsCGI
  fix_module_name:
    - from: Template::Toolkit
      to:   Template
  fix_package_depends: []
  no_depends:
    - module: mod_perl
  skip_name_resolve_modules: []
modules: []
