---
global:
  fix_module_name:
    - from: Template::Toolkit
      to:   Template
    - from: Class::Classgen::classgen
      to: Class::Classgen::Attribute
  fix_package_depends: []
  no_depends:
    - module: mod_perl
    - module: IO::Compress
  skip_name_resolve_modules: []
modules:
  - module: IO::Compress
    skip_build: 1
  - module: IO::Compress::Zlib
    skip_test: 1
  - module: Compress::Raw::Zlib
    skip_test: 1
  - module: HTTP::Engine
    skip_test: 1
  - module: Moose
    skip_test: 1
  - module: MooseX::Types
    skip_test: 1
  - module: MooseX::MethodAttributes
    skip_test: 1
  - module: MooseX::Emulate::Class::Accessor::Fast
    skip_test: 1
  - module: Catalyst::Runtime
    skip_test: 1
  - module: MooseX::SemiAffordanceAccessor
    skip_test: 1
  - module: File::ChangeNotify
    skip_test: 1
  - module: Catalyst::Plugin::Static::Simple
    skip_test: 1
  - module: Catalyst::Plugin::ConfigLoader
    skip_test: 1

