---
global:
  cpan_mirrors:
    - http://ftp.jaist.ac.jp/pub/CPAN/
  fix_module_name: []
  fix_package_depends: []
  no_depends:
    # default
    - module: perl
    - module: mod_perl
    - module: version
    # PathTools
    - module: File::Copy
    - module: File::Spec
    - module: File::Spec::Functions
    - module: File::Spec::Mac
    - module: File::Spec::OS2
    - module: File::Spec::Unix
    - module: File::Spec::Win32
    - module: File::Temp
    - module: File::chdir
    - module: PathTools
    # IO Compress
    - module: IO::Compress
    - module: IO::Compress::Gzip
    - module: IO::Compress::Bzip2
    - module: IO::Compress::Base
    - module: IO::Compress::Zlib
    - module: Compress::Raw::Zlib
    - module: Compress::Zlib
    - module: IO::Zlib
    # Testing
    - module: Text::Exception
    - module: Test::Simple
    - module: Test::Harness
    # other
    - module: CGI
    - module: Class::Accessor
    - module: Class::Accessor::Fast
    - module: Cwd
    - module: Devel::PPPort
    - module: Encode
    - module: ExtUtils::MakeMaker
    - module: 'Filter # brokes?'
    - module: HTTP::Request
    - module: HTTP::Response
    - module: IO::stringy
    - module: kurila
    - module: List::Util
    - module: Module::Install
    - module: Module::Install::AuthorTests
    - module: Pod::Parser
    - module: Scalar::List::Utils
    - module: Scalar::Util
    - module: Sub::Uplevel
  skip_name_resolve_modules: []

modules:
  - module: CGI::Simple
    no_depends:
     - module: IO::Scalar
  - module: Test::Exception
    depends:
      - module: Test::Simple
    no_depends:
      - module: Test::Builder::Tester
  - module: FindBin::libs
    skip_test: 1
  - module: HTTP::Request::AsCGI
    skip_build: 1
  - module: IO::Compress::Base
    skip_build: 1
  - module: MooseX::MethodAttributes::Inheritable
    skip_build: 1
  - module: Perl::MinimumVersion
    skip_test: 1
  - module: PathTools
    skip_build: 1
  - module: Scalar::List::Utils
    skip_build: 1
  - module: Module::Setup
    no_depends:
      - module: Module::Install::AuthorTests
  - module: Catalyst::Runtime
    no_depends:
      - module: HTTP::Request::AsCGI
      - module: Test::Exception
  - module: Acme
    custom:
      tgz_path: ~/.cpanpackager/custom_module/Acme-1.11111.tar.gz
      dist_name: Acme
      version: 1.2
